build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.20
  use_build_cache: true
images:
- context_dir: .ibm/images
  dockerfile_path: Dockerfile
  to: showcase-e2e-runner
  run_if_changed: ^.ibm/images/
promotion:
  to:
    - name: rhdh
      namespace: ci
    - name: quay.io/rhdh-community/rhdh-e2e-runner
      namespace: quay
      tag: main
releases:
  latest:
    release:
      architecture: amd64
      channel: fast
      version: "4.15"
resources:
  '*':
    limits:
      memory: 5Gi
    requests:
      cpu: 500m
      memory: 2Gi
tests:
- as: e2e-tests
  skip_if_only_changed: ^docs/|showcase-docs/|^\.changeset/|CONTRIBUTING\.md|OWNERS|README\.md|USAGE_DATA\.md|^scripts/|^\.github/|\.threatmodel/|^ui/|\.md$
  steps:
    test:
    - ref: redhat-developer-rhdh-release-1.4
    - ref: redhat-developer-rhdh-release-1.4-mirror
- as: e2e-tests-nightly
  cron: 0 4 * * *
  steps:
    test:
    - ref: redhat-developer-rhdh-release-1.4-nightly
    - ref: redhat-developer-rhdh-release-1.4-mirror-nightly
zz_generated_metadata:
  branch: release-1.4
  org: redhat-developer
  repo: rhdh
